Globs:
  - "**/*.cr"
  - "!bin"
  - "!lib"

Documentation/Documentation:
  Enabled: true

Layout/LineLength:
  Enabled: true
  MaxLength: 120

Lint/ComparisonToBoolean:
  Enabled: true

Style/GuardClause:
  Enabled: true
Style/LargeNumbers:
  Enabled: true
