Excluded:
  - "bin"
  - "lib"
  - "db"

Layout/LineLength:
  Enabled: true
  MaxLength: 120

Lint/ComparisonToBoolean:
  Enabled: true

Style/GuardClause:
  Enabled: true
Style/LargeNumbers:
  Enabled: true
