/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../src/components/base/BaseButton.vue')['default']
    BaseContainer: typeof import('./../src/components/base/BaseContainer.vue')['default']
    BaseForm: typeof import('./../src/components/base/BaseForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskTable: typeof import('./../src/components/TaskTable.vue')['default']
  }
}
