/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Root': RouteRecordInfo<'Root', '/', Record<never, never>, Record<never, never>>,
    'UsersSignIn': RouteRecordInfo<'UsersSignIn', '/users/sign_in', Record<never, never>, Record<never, never>>,
    'UsersSignOut': RouteRecordInfo<'UsersSignOut', '/users/sign_out', Record<never, never>, Record<never, never>>,
    'UsersSignUp': RouteRecordInfo<'UsersSignUp', '/users/sign_up', Record<never, never>, Record<never, never>>,
  }
}
