name: TypeScript
on:
  pull_request:
  push:
    branches: [master]
jobs:
  eslint:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run TypeScript
        run: npm run tsc
