require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/LineLength:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: "space"

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Metrics/MethodLength:
  Enabled: true
  CountAsOne: ["array", "hash", "heredoc", "method_call"]

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: braces_for_chaining
Style/IfUnlessModifier:
  Enabled: true
Style/MultilineTernaryOperator:
  Enabled: true
Style/RegexpLiteral:
  Enabled: true
  AllowInnerSlashes: true
