source "https://rubygems.org"

ruby "3.3.0"

# Object-relational mapper framework
# [https://github.com/rails/rails]
gem "activerecord", "~> 7.1.3.2"

# A Ruby binding for the OpenBSD bcrypt() password hashing algorithm
# [https://github.com/bcrypt-ruby/bcrypt-ruby]
gem "bcrypt", "~> 3.1.20"

# A ruby implementation of the RFC 7519 OAuth JSON Web Token (JWT) standard
# [https://github.com/jwt/ruby-jwt]
gem "jwt", "~> 2.8.0"

# The ruby interface for PostgreSQL
# [https://github.com/ged/ruby-pg]
gem "pg", "~> 1.5.4"

# A Ruby/Rack web server built for parallelism
# [https://github.com/puma/puma]
gem "puma", "~> 6.4.2"

# A make-like build utility for Ruby
# [https://github.com/ruby/rake]
gem "rake", "~> 13.1.0"

# Classy web-development dressed in a DSL
# [https://github.com/sinatra/sinatra]
gem "sinatra", "~> 4.0.0"

# Extends Sinatra with ActiveRecord helper methods and Rake tasks
# [https://github.com/sinatra-activerecord/sinatra-activerecord]
gem "sinatra-activerecord", "~> 2.0.27"

# Cross Origin Request Sharing extension for Sinatra
# [https://github.com/britg/sinatra-cross_origin]
gem "sinatra-cross_origin", "~> 0.3.1"

group :development do
  # Make your Rubies go faster with this command line tool highly inspired by fast-ruby
  # [https://github.com/DamirSvrtan/fasterer]
  gem "fasterer", "~> 0.11.0"

  # Restarts an app when the filesystem changes
  # [https://github.com/alexch/rerun]
  gem "rerun", "~> 0.14.0"

  # An extension to RuboCop focused on Performance optimization analysis
  # [https://github.com/rubocop/rubocop-performance]
  gem "rubocop-performance", "~> 1.20.2", require: false

  # A linter & formatter built on RuboCop that brings the ethos of StandardJS to Ruby
  # [https://github.com/standardrb/standard]
  gem "standard", "~> 1.33.0"
end

group :development, :test do
  # Strategies for cleaning databases using ActiveRecord. Can be used to ensure a clean state for testing
  # [https://github.com/DatabaseCleaner/database_cleaner-active_record]
  gem "database_cleaner-active_record"

  # A Ruby gem to load environment variables from `.env`
  # [https://github.com/bkeepers/dotenv]
  gem "dotenv", "~> 3.0.3"

  # A library for setting up Ruby objects as test data
  # [https://github.com/thoughtbot/factory_bot]
  gem "factory_bot", "~> 6.4.6"

  # Step-by-step debugging and stack navigation in Pry
  # [https://github.com/deivid-rodriguez/pry-byebug]
  gem "pry-byebug", "~> 3.10.1"

  # A small, simple testing API for Rack apps
  # [https://github.com/rack/rack-test]
  gem "rack-test", "~> 2.1.0"

  # Rspec provides the structure for writing executable examples of how your code should behave
  # [https://github.com/rspec/rspec-core]
  gem "rspec", "~> 3.13.0"
end
