source "https://rubygems.org"

ruby "3.3.0"

# A Ruby/Rack web server built for parallelism
# [https://github.com/puma/puma]
gem "puma", "~> 6.4.2"

# Classy web-development dressed in a DSL
# [https://github.com/sinatra/sinatra]
gem "sinatra", "~> 4.0.0"

group :development do
  # Make your Rubies go faster with this command line tool highly inspired by fast-ruby
  # [https://github.com/DamirSvrtan/fasterer]
  gem "fasterer", "~> 0.11.0"

  # An extension to RuboCop focused on Performance optimization analysis
  # [https://github.com/rubocop/rubocop-performance]
  gem "rubocop-performance", "~> 1.20.2", require: false

  # A linter & formatter built on RuboCop that brings the ethos of StandardJS to Ruby
  # [https://github.com/standardrb/standard]
  gem "standard", "~> 1.33.0"
end

group :development, :test do
  # Step-by-step debugging and stack navigation in Pry
  # [https://github.com/deivid-rodriguez/pry-byebug]
  gem "pry-byebug", "~> 3.10.1"

  # Restarts an app when the filesystem changes
  # [https://github.com/alexch/rerun]
  gem "rerun", "~> 0.14.0"
end
