name: Express

on:
  pull_request:
    paths:
     - node/express/**
  push:
    branches: [master]
    paths:
     - node/express/**

jobs:
  eslint:
    name: EsLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ./node/express
      - name: Run esLint
        run: npm run lint
        working-directory: ./node/express

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ./node/express
      - name: Run TypeScript
        run: npm run tsc
        working-directory: ./node/express

  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql user: test
          postgresql password: password
      - name: Build app
        run: |
          npm install
          npx prisma db push
        working-directory: ./node/express
        env:
          DATABASE_URL: 'postgres://test:password@localhost/application_test'
      - name: Run Vitest
        run: pnpm test
        working-directory: ./node/express
        env:
          DATABASE_URL: 'postgres://test:password@localhost/application_test'
